feat(python): upgrade python from 3.11 to 3.12 everywhere in codebase
This required updating `snapshottest` package to a pre-release version
that contained support for Python 3.12, either that or changing the
package to another snapshot test package that would've been Python 3.12
compatible using a stable version.

The previously used `snapshottest` v0.6.0 failed when running
"pytest . -vv" with:
```
ModuleNotFoundError: No module named 'imp'
```

refs PT-1872